var slider = tns({
    container: '#responsive',
    responsive: {
        320: {
            items: 1,
            center: true,
            fixedWidth: 287,
            loop: false,
            swipeAngle: true,
            speed: 400,
            gutter: 30,
            rewind: true,
            startIndex: 2,
            controlsText: ['', ''],
        },
        768: {
            fixedWidth: 731,
            startIndex: 2,
            gutter: 70,
            items: 1,
            center: true,
            loop: false,
            swipeAngle: true,
            speed: 400,
            rewind: true,
            controlsText: ['', ''],
        },
        1160: {
            fixedWidth: 731,
            startIndex: 2,
            gutter: 70,
            items: 1,
            center: true,
            loop: false,
            swipeAngle: true,
            speed: 400,
            rewind: true,
            controlsText: ['', ''],
        },
    },
});
